### ISSUE TITLE
regarding torrents

### ISSUE THREAD

**Issue by shawngraham** [JonathanReeve/dh-usb#7]
Hi,

I'm thinking of trying dh-usb out in one of my upcoming classes, requiring students to put it on a usbstick etc... but regarding torrents, the uni's systems are going to make that rather awkward. Suggestions for other relatively low-friction ways of doing this? Target students are neophytes in most things digital...

**Comment by JonathanReeve** [comment]
Hi Shawn,

That's awesome that you're interested in trying out DH-USB with your class. It can be like a big beta-test. So far it's worked on _almost_ all machines I've tried it out on. 

At the moment, the seedbox that serves the torrent is the only place I have the image. Since the file is so big (5GB), it's too big for any of the other servers I have access to, at the moment. Here are some other ways that you might be able to get it out to your class: 

 - If your university has a small budget for course materials, you could buy a bunch of $10 32GB drives, and write the image to them all. (I think CloneZilla can do concurrent clones.) Provided you download the torrent from home, first. This way you'll have some drives for the next course, too. 
 - You could download the image via bittorrent from outside the university network, and then serve it over FTP or something for your students to download. 
 - You could make a few USB disks at home, and then have a copying party where everyone copies everyone else's disks during class. 

Ideally it'd be like with other Linux distributions, where universities around the world share the burden by mirroring the ISOs over FTP. At the moment, the torrent was the best thing I could think of. I'd love to hear any other ideas you might have, though.

**Comment by shawngraham** [comment]
Cool! FTP might be the way to go with this gang, as I don't actually see them in person. Right now, I'm trying to persuade Chrome that the bittorrent client is not in fact malicious software...

oh, wait, utorrent will install. Alright!

**Comment by shawngraham** [comment]
hmmm. installing to the stick with unetbootin, I end up with this...

<img width="669" alt="screen shot 2017-02-23 at 9 22 04 pm" src="https://cloud.githubusercontent.com/assets/4266026/23287895/486864e0-fa0e-11e6-965e-8e7310c0d35b.png">
<img width="494" alt="screen shot 2017-02-23 at 9 22 14 pm" src="https://cloud.githubusercontent.com/assets/4266026/23287897/4e4f22c2-fa0e-11e6-8da6-52b041ee3d6a.png">

**Comment by shawngraham** [comment]
...which seems not likely? searching out a windows machine...

**Comment by JonathanReeve** [comment]
I haven't actually tested it with UNetbootin, I just assumed it writes .img files to a USB disk. That's weird that it seems to be trying to install syslinux. It shouldn't do that. (It should just just write the contents of the .img to the disk verbatim.) Did you make sure to select the .img option, and not .iso? If so, I might have to remove unetbootin from the instructions, since it shouldn't be trying to install a bootloader.  

You might try using `dd` instead, per the alternative instructions. Also, I'll look around for another MacOS program that can write .img files.

**Comment by JonathanReeve** [comment]
So this guide seems to think you can write .img files to a disk using Disk Utility: http://craiccomputing.blogspot.com/2007/06/copying-disk-image-to-usb-memory-stick.html

**Comment by shawngraham** [comment]
hmmm. almost - but now an error message that suggests to me that something happened during the download?

<img width="729" alt="screen shot 2017-02-23 at 9 36 36 pm" src="https://cloud.githubusercontent.com/assets/4266026/23288233/48573c4a-fa10-11e6-8519-b84023c1b1f4.png">

**Comment by shawngraham** [comment]
re earlier point, I did have the img option selected ("floppy"), just went back and doublechecked, same result.

**Comment by shawngraham** [comment]
giving dd a try...

**Comment by shawngraham** [comment]
the alternative instructions worked! i have it up and running on my other machine - looking forward to playing with it!
